### PR TITLE
New logo!

### PR DESCRIPTION
**Pull request by betanalpha**
Added the new logos -- I'll let someone else confirm and merge.

### CODE REVIEW

**Comment by syclik** [comment]
did you intend to just remove old artwork? If so, maybe we should tag versions. Just let me know if that was intentional.

**Comment by betanalpha** [comment]
Yeah, it was intentional.  I thought it would be confusing
to have both versions at the same time.  Definitely go
for a tag.

**Comment by bob-carpenter** [comment]
I agree.  That's what version control's for --- so you
don't need the whole history staring you in the face in
every project.
- Bob

**Comment by syclik** [comment]
Ok. I tagged the original with v1.0.

**Pull request merged**
